.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. blinkhash_qt test_blinkhash_qt
clean: FORCE
	$(MAKE) -C .. blinkhash_qt_clean test_blinkhash_qt_clean
check: FORCE
	$(MAKE) -C .. test_blinkhash_qt_check
blinkhash-qt blinkhash-qt.exe: FORCE
	 $(MAKE) -C .. blinkhash_qt
apk: FORCE
	$(MAKE) -C .. blinkhash_qt_apk
